import "@/app/globals.css"
import Navbar from "@/components/Admin/Navbar";


export const metadata = {
  title: "Saffy",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
    <Navbar />
    {children}
    
    </>
  );
}
