
import "@/app/globals.css";
import { TooltipProvider } from "@/components/ui/tooltip";


export const metadata = {
  title: "Saffy",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
    <TooltipProvider>
      {children}
    </TooltipProvider>
    
    </>
  );
}
